// Ensure you have loaded your decompressor.js in your HTML: 
// <script src="./Decompressor/decompressor.js"></script>

async function handleFile(file) {
    // 1. Get the Factory function (exported by your emscripten build)
    const factory = decompressor; 

    // 2. Initialize the WASM Module
    const instance = await factory({
        // Set up standard output/error capture
        print: (text) => console.log("WASM Output: ", text),
        printErr: (text) => console.error("WASM Error: ", text),
    });

    // 3. Convert your file to an ArrayBuffer
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);

    // 4. Write the file into the virtual filesystem
    // We name it input.huff so your C code can find it
    const inputFileName = "input.huff";
    instance.FS.writeFile(inputFileName, uint8Array);

    try {
        console.log("Starting Decompression...");
        
        // 5. Trigger your C 'main' function
        // This corresponds to: ./decompressor input.huff
        instance.callMain([inputFileName]);

        // 6. Read the output file generated by your C code
        // Update 'output_file' to the exact name your C code generates
        const outputData = instance.FS.readFile("output_file");
        
        console.log("Decompression Successful!", outputData);
        return outputData;

    } catch (err) {
        console.error("Decompression failed:", err);
    }
}

// Example usage with your HTML input:
document.getElementById('compress-form').onsubmit = async (e) => {
    e.preventDefault();
    const fileInput = document.querySelector('input[type="file"]');
    if (fileInput.files.length > 0) {
        await handleFile(fileInput.files[0]);
    }
};